name = "semantic-qa-worker"
main = "cloudflare-worker.js"
compatibility_date = "2025-07-28"
compatibility_flags = ["nodejs_compat"]

[vars]
# Add any non-secret environment variables here if needed

# Secrets (use `wrangler secret put <KEY>` to set these):
# WEAVIATE_URL
# WEAVIATE_API_KEY  
# OPENAI_API_KEY 